### PRUEBA DEL SISTEMA JUGADOR (SIN LOMBOK)

### 1. Registrar un Usuario Normal
# Esperamos: "Registro Exitoso"
POST http://localhost:8080/api/gamers/register
Content-Type: application/json

{
  "nickname": "ComandantePepe",
  "password": "123"
}

### 2. Intentar registrar el mismo (Debe fallar)
# Esperamos: "Error: El Nickname ya existe"
POST http://localhost:8080/api/gamers/register
Content-Type: application/json

{
  "nickname": "ComandantePepe",
  "password": "otra"
}

### 3. Login Correcto
# Esperamos: "Bienvenido ComandantePepe"
POST http://localhost:8080/api/gamers/login
Content-Type: application/json

{
  "nickname": "ComandantePepe",
  "password": "123"
}

### 4. Login Incorrecto
# Esperamos: "Error: Credenciales incorrectas"
POST http://localhost:8080/api/gamers/login
Content-Type: application/json

{
  "nickname": "ComandantePepe",
  "password": "ClaveFalsa"
}

### 5. Jugar como Invitado (NUEVO)
# Esperamos: "Entraste como invitado: Guest_XXXX"
POST http://localhost:8080/api/gamers/login-guest
Content-Type: application/json